{
	"version": 1627266016,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"img/setaesqeurda-sheet0.png",
		"img/setadireita-sheet0.png",
		"img/escolhapersonagem-sheet0.png",
		"img/elevador-sheet0.png",
		"img/personagem-sheet0.png",
		"img/personagem-sheet1.png",
		"img/porta-sheet0.png",
		"img/porta-sheet1.png",
		"img/painelelevador-sheet0.png",
		"img/janelas-sheet0.png",
		"img/imagem1-sheet0.png",
		"img/imagem2-sheet0.png",
		"img/imagem3-sheet0.png",
		"img/molduravideos-sheet0.png",
		"img/parede1-sheet0.png",
		"img/parede2-sheet0.png",
		"img/parede3-sheet0.png",
		"img/tijolo.png",
		"img/imagemzoom-sheet0.png",
		"img/placa-sheet0.png",
		"img/setapbaixo-sheet0.png",
		"img/setapcima-sheet0.png",
		"img/chaoembolada.png",
		"img/parede1_embolad-sheet0.png",
		"img/parede2_embolada-sheet0.png",
		"img/chaoescada-sheet0.png",
		"img/paredeescada-sheet0.png",
		"img/parede3_embolada-sheet0.png",
		"img/parede4_embolada-sheet0.png",
		"img/molduravideos_embolada-sheet0.png",
		"img/placaembolada-sheet0.png",
		"img/parede5_embolada-sheet0.png",
		"img/parede6_embolada-sheet0.png",
		"img/chaocantostrabalho.png",
		"img/balao-sheet0.png",
		"img/imagem_jongo-sheet0.png",
		"img/imagem_jongo2-sheet0.png",
		"img/imagem_jongo3-sheet0.png",
		"img/imagem_jongo4-sheet0.png",
		"img/imagem_jongo5-sheet0.png",
		"img/imagem_jongo6-sheet0.png",
		"img/imagem_jongo7-sheet0.png",
		"img/imagem_jongo8-sheet0.png",
		"img/molduravideos2-sheet0.png",
		"img/catiraimagem1-sheet0.png",
		"img/catiraimagem2-sheet0.png",
		"img/catiraimagem3-sheet0.png",
		"img/moldura-sheet0.png",
		"img/chaosolido-sheet0.png",
		"img/plaquinha-sheet0.png",
		"img/limitetela-sheet0.png",
		"img/teste-sheet0.png",
		"img/camera-sheet0.png",
		"project/feijao.m4a",
		"project/feijao.ogg",
		"project/minervina.m4a",
		"project/minervina.ogg",
		"project/gaviao.m4a",
		"project/gaviao.ogg",
		"project/buy something! (radio edit).ogg",
		"project/professor de embolada.m4a",
		"project/professor de embolada.ogg",
		"project/jongo da serrinha 1.m4a",
		"project/jongo da serrinha 1.ogg",
		"project/jongo da serrinha 2.m4a",
		"project/jongo da serrinha 2.ogg",
		"project/340750__soundslikewillem__05-elevator-bing.m4a",
		"project/340750__soundslikewillem__05-elevator-bing.ogg",
		"project/346212__inspectorj__door-squeak-normal-d.m4a",
		"project/346212__inspectorj__door-squeak-normal-d.ogg",
		"project/431118__inspectorj__door-front-closing-a.m4a",
		"project/431118__inspectorj__door-front-closing-a.ogg",
		"project/elevador.m4a",
		"project/elevador.ogg",
		"project/favoritos do catira - visitando o sertão.m4a",
		"project/favoritos do catira - visitando o sertão.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"bata do milho.mp4",
		"feijao.mp4",
		"lavadeiras.mp4",
		"rede.mp4",
		"cacau.mp4",
		"caju e castanha.mp4",
		"jongo danca.mp4"
	]
}